{{- if .Values.kafka.enabled }}
{{- if .Values.kafka.externalAccess.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-broker-ext
  labels:
    run: kafka-broker
    app.kubernetes.io/name: kafka-broker-ext
    app.kubernetes.io/component: kafka
    {{- include "vkb.labels" $ | nindent 4 }}
spec:
  ports:
    - name: kafka-svc-ext
      port: 9093
      protocol: TCP
      targetPort: kafka-app-ext
      nodePort: {{ .Values.kafka.externalAccess.nodePort }}
  type: NodePort
  selector:
    run: kafka-broker
    {{- include "vkb.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
